### ISSUE TITLE
Question : Windows Patch

### ISSUE THREAD

**Issue by rootinshell** [sumdog/alfresco-tracking-removal#4]
is there anyway to apply this patch into windows environnement ?

**Comment by sumdog** [comment]
The `amp` directory should contain a version that can be built into an amp/alfresco plugin. It should work on all environments. I no longer work on Alfresco and haven't maintained this in years; so I'm not sure if it will work with current versions. The blog post in the README explains how it works, so it should be easy to write your own.

Pull requests are welcome.
